#include <SDL.h>
#include <iostream>
#include "barier.hpp"

using namespace std;
/** \brief this class is handling the brown barriers in our game 
 * These barriers are basically generated by using the functions that set its location
 * The position of the barrier is defined 
 * And then the barrier is finally drawn 
 */
void Bari::locat()
{
    if (countB == 0)
    {
        b = 1180;
    }
    else if (countB == 1)
    {
        b = 1230;
        countB = -1;
    }
    if (moverRect.x < -50)
    {
        moverRect.x = 1200;
        moverRect.y = (rand() % 600);
    }

    countB++;
    moverRect.x -= 6;
}

Bari::~Bari()
{
}

SDL_Rect Bari::posi()
{
    return moverRect;
}

void Bari::draw(SDL_Renderer *gRenderer, SDL_Texture *assets)
{
    locat();
    srcRect = {2741, 311, 108, 239};
    Unit::draw(gRenderer, assets);
}

Bari::Bari()
{
    moverRect = {400, 450, 50, 200};
}

Bari::Bari(int x, int y)
{
    moverRect = {x, y, 70, 200};
}